### ISSUE TITLE
Fatal error beim Buchen

### ISSUE THREAD

**Issue by RalphBike** [flotte-berlin/commons-booking-admin-booking#1]
Beim Erstellen einer Admin-Buchung bekomme ich folgende Fehlermeldung. Die Buchung wird trotzdem angelegt, die Meldung wirkt aber nicht sehr vertrauenserweckend. Bei Rückfragen gerne melden, danke!

`Fatal error: Uncaught Error: Call to undefined function get_thumb() in /path_on_my_server/wordpress/wp-content/plugins/commons-booking-admin-booking/classes/class-cb-admin-booking-admin.php:607 Stack trace: #0 /path_on_my_server/wordpress/wp-content/plugins/commons-booking-admin-booking/classes/class-cb-admin-booking-admin.php(565): CB_Admin_Booking_Admin->set_booking_vars(Object(CB_Booking)) #1 /path_on_my_server/wordpress/wp-content/plugins/commons-booking-admin-booking/classes/class-cb-admin-booking-admin.php(293): CB_Admin_Booking_Admin->create_booking('2020-08-18', '2020-11-06', 895, 1, 'confirmed', '582', true, 'Nemo defekt.') #2 /path_on_my_server/wordpress/wp-content/plugins/commons-booking-admin-booking/classes/class-cb-admin-booking-admin.php(455): CB_Admin_Booking_Admin->handle_booking_form_submit(Array) #3 /path_on_my_server/wordpress/wp-content/plugins/commons-booking-admin-booking/classes/class-cb-admin-booking-admin.php(34): CB_Admin_Booking_Admin->render_booking_crea in /path_on_my_server/wordpress/wp-content/plugins/commons-booking-admin-booking/classes/class-cb-admin-booking-admin.php on line 607`

**Comment by poilu** [comment]
Ist das Commons Booking Plugin aktiviert? Das ist eine Funktion von CB, die da aufgerufen und nicht gefunden wird.

**Comment by RalphBike** [comment]
Klar. Liegt es vielleicht an der Version? Wir verwenden 0.9.4.10, das ist die aktuelle auf dem "alten" Branch.

**Comment by poilu** [comment]
Guter Hinweis, mit der Version. Das Problem wurde tatsächlich durch Umbenennungen der Helper Functions im CB commit https://github.com/wielebenwir/commons-booking/commit/fc5224cd4d942a2413fe6bcbcdf3b31cd24ec255 verursacht. Dabei wurde auch offenbar, dass die Template Tags {{ITEM_THUMB}} und {{LOCATION_THUMB}} nicht fukntionieren, da die Funktion keinen Rückgabewert liefert. Ich werde ein entsprechendes Ticket für Commons Booking anlegen.
Der Bug Fix fürs Admin Booking Plugin ist in den Releases
https://github.com/flotte-berlin/commons-booking-admin-booking/releases/tag/v0.1.8
https://github.com/flotte-berlin/commons-booking-admin-booking/releases/tag/v0.2.8
zu finden.
